baseURL = "https://blueskyhealth.netlify.app/"

languageCode = "en-us"
title = "Blue Sky Health Ltd."
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "About"
url = "about/"
weight = 2
#[[menu.main]]
#name = "Service"
#url = "service/"
#weight = 3
#[[menu.main]]
#name = "Gallery"
#url = "gallery/"
#weight = 4
#[[menu.main]]
#name = "Blog"
#url = "blog/"
#weight = 5
#[[menu.main]]
#name = "Contact"
#url = "contact/"
#weight = 6

# Site Params
[params]
home = "Home"
logo = "images/logo.png"
dateFormat = "6 January 2006"
# Meta data
description = "Airspace Hugo theme"
author = "Themefisher"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable = true
bgImage = "images/services.jpg"
heading = "Welcome to Blue Sky Health Ltd"
description = "A complete Diagnostic Center with all services."
# button
btn = true
btnText = "Learn More"
btnURL = "https://www.facebook.com/BlueskyHealthLtd/"

# flip text
[[params.banner.flipText]]
title = "Top-notch quality"
[[params.banner.flipText]]
title = "Latest Technology"
[[params.banner.flipText]]
title = "Qualified Doctors"

# Homepage About Section
[params.about]
enable = true
title = "Our Services"
content = "Blue Sky Health is a modern diagnostic centre equipped with cutting-edge medical technologies imported from japan including the latest 64 slice city scan machine. We're offering a range of services including imaging and pathology. You can easily book our services by calling our hotline number. We have a team of highly qualified doctors available to provide you consultation on any issue."
image = "images/service2.jpg"

# Call to Action
[params.cta]
enable = true
title = "Contact Us to set your Appointment"
content = "Call on our hotline number 01958277500 to set your appointment now!<br>Email: blueskyhealthltd@gmail.com"
btnText = "Connect with Us"
btnURL = "https://www.facebook.com/BlueskyHealthLtd/"

# Portfolio Section On Homepage
[params.portfolio]
enable = true
title = "Our Doctors"
subtitle = "We have a team of highly experienced, skillful doctors dedicated to provide our patients with world-class healthcare. Our doctors are assisted by seasoned nurses and technologists."

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "#"

[[params.socialIcon]]
icon = "ion-email"
url = "#"

[[params.socialIcon]]
icon = "ion-call-48-filled"
url = "#"


